// Code generated by command: go run main.go -pkg simd -out ../kernels_amd64.s -stubs ../kernels_amd64.go. DO NOT EDIT.

//go:build amd64 && !purego

package simd

func sad16x16(src []byte, srcStride int, ref []byte, refStride int) int

func sad16x8(src []byte, srcStride int, ref []byte, refStride int) int

func sad8x16(src []byte, srcStride int, ref []byte, refStride int) int

func sad8x8(src []byte, srcStride int, ref []byte, refStride int) int

func sad8x4(src []byte, srcStride int, ref []byte, refStride int) int
